# Generated by Django 4.2 on 2024-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
