# Generated by Django 4.2 on 2024-10-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmasite', '0002_services_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='short_desc',
        ),
    ]
