# Generated by Django 4.2 on 2024-10-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmasite', '0007_contactuspage_missionandvision_mycv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCV',
            new_name='Brochure',
        ),
    ]
