# Generated by Django 4.2 on 2024-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmasite', '0008_rename_mycv_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionandvision',
            name='vision_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='book',
            field=models.FileField(blank=True, help_text='Upload your brochure Here', null=True, upload_to='media'),
        ),
    ]
